---

- name: Clone inwx client
  git:
    repo: "https://github.com/TheTesla/python2.7-client.git"
    dest: "/root/inwx-client"

- name: Copy update bash script
  copy:
    src: "../files/root/inwxupdate.bash"
    dest: "/root/inwxupdate.bash"
    mode: 0744

- name: Escape dkimkey
  set_fact:
    dkimkeyescaped: "{{ dkimkey|replace('\"','\\\"') }}"

- debug: 
    msg: "{{ dkimkeyescaped }}"

- name: "Update domain {{ item }} on inwx"
  shell: "/root/inwxupdate.bash \"{{ inwxapi }}\" \"{{ inwxlogin }}\" \"{{ inwxpasswd }}\" \"{{ item.split('.',1)[0] }}\" \"{{ item.split('.',1)[1] }}\" \"{{ myextip }}\" \"{{ myextip6 }}\" \"{{ dkimkeyescaped }}\" 600" 
  args:
    executable: "/bin/bash"
  with_items:
    - "{{ domain }}"
    - "{{ secondarydomains }}"
  ignore_errors: yes


