dist: focal
language: python
addons:
  apt:
    packages:
      - python3
      - rspamd
      - libcurl4-openssl-dev
      - libssl-dev
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
- sudo cat > /etc/sudoers.d/some-daemon << SUDO
  bob ALL= NOPASSWD: /bin/systemctl restart some-daemon.service
  bob ALL= NOPASSWD: /bin/systemctl stop some-daemon.service
  bob ALL= NOPASSWD: /bin/systemctl start some-daemon.service
  SUDO

script:
- python3 -m unittest discover
stages:
- deploy
deploy:
  provider: pypi
  user: __token__
  password:
    secure: HIH+tEVaiNmV6l+DUzVnVy2Y70nBKdpzUND8yLtaAzAg31RScTvJh+roVgELm4A+v7A9hbjxrw88ApEqWuLHBlRs3/KKnbcnfG1tQXiygaYAXufsGA/68Z39w+QzF3ioFpE7TeccPduDLhzu9/0LJ+DG4bGer+qrrATMnpld9iJtSP9HhbpkBULyqs33uaWEPYLfE3I2q/pUK8sM7v94ca6Djlco75lLsKGu5ayoMGyQ33pPiKk1vc0w8dvvmOSZhMZjNldowXLW+bevOltDvZ3OsWUigAD1Ob8szSf2FxR9ZwYOnoXaRoVjg3roiBKB13MZsgDvnTyrmIQijepaOTInMLLsBM2XRQGNWY7WQf1o2kqOQIvn/4cEfcWS7yzWkLXsTZfU6uQV+Pnu6jMden1iMOpLuCdmSjrWPN1QVyk1ADEfy3vDLhZIJNMfJywe3pC4/Q8NyPhJMXR3q6KI+p0LXPKBfm6CPlkdjc48Yet/z0YEK54oUOulRUhHVmeJL/CdUzvgjeFLA+9IGwuuYSsWj/Iu62chYAXsphKUGqxfermb78Mt0yqPoRx6Fs1wSBD1GLHhTiMCZYte2oKsMc9KGpZAbK9rd7lMWdL8kdLIpBvhjIP6Rv7qYHKsueCwGBw8Vk4GVyeKIrtYJIxiVL67pIQNPK2Tr3jcqa2Wk2E=
