dist: focal
language: python
env:
  matrix:
  - PYTHONIOENCODING=utf-8
  global:
    secure: a/7qK6LrsmJk5MLkM2ZmKT36fFD0H3V+IplVi2sBXLjLMMaRA1gL4eb7lpkhCdkOFtpOTJ3gL0+X7hpFSSNIjPbHJmus0nwsp5rONvtRlxyp3cuGCK71968gejF6IY29sB87zcVTGfdWDIi6paJlhG4QEJKv0t/mTWxMs6zeQFbVgCWVu7rFeoyabf5C7EggSsn1gsThH0iTcLm60XJgnkJoQmDtTsPyAmtJGft9+GJaQiaLHz2u7LSuQd3r08zuVR/ji/DUDt/lfXGX0TSY/EmwrP49tV+GPfWGfw/gW1CnA6/ngj406KhHoB1c6uiAudr5ti4PHg23Bb1xe1NAcdCmV6LAarCKl4hs//CTqLvv75bPAA55pMMVhvzSWqBS8OU29w0NmHyG7/1RCgLcYjjsbJ7zMTBDRmsS4BZcrWZKeJkYGct9yAPgOz2FtCs040Ka+3Y6pncRitOcDjVv5+FN2NIfR4EbgArLBSjfxRUEY/BBMcGmuCVwLAKxCAF2/asxa6ELrXAwZIJTHIZ21GCwbtq1w4UVbTtbTnPd4vwzikSm+EaJlnJuS6ysE5nQjs5ylhDHKw3O+ZxesMY5GAD3LSM8U+sbN8S5NvohrHUPd4G3AfFAP4Edpw7G5QWy6BSpMrpqYBAML/cOzBmpqNtaZ7TdEPTY7Bwtu/FmqKY=
python:
- '3.8'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
    - postfix
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
script:
- echo "hello"
stages:
- deploy
after_success:
- echo "${DOCKER_PASSWORD:0:5}"
- echo "$DOCKER_PASSWORD" | docker login -u entroserv --password-stdin
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: vYysmnM+BTHfH3arLIkjttwKTDeqHOyWuhHfaVC8acUU7Fvc06hJtD7J8IMsdEeKe6H0qnz4lhK3QCCMKXWgh3lBHpSGMzvklkAbcna7wr+bgiARn1NLG3Gs+U1YqMagUBWQoi5LlRSjbYwNqiLh78xA85WXXLF1NPvNuy9nOdNF7VTIhSY+fT8/HtpHoFhy0cN2+WWb6EWJGdp+uB8t4PP3x436WjA6NsRI1T4XNXALFuv10puoi+oEFpHe9iGqKlYyNTtA9UyM1oSJpvxMJD+ISOgcYgi67i84MRsVLC/krV9u/JBFauL5gCeQEDLg60El8zz0kGH8PONM3EM4SdIrzKCNoOha+W08N42BzpSWOoj1J8FdZHnLPnZNH+VjbZCG/5iN5yiBOG5DzKKmy0d4fUcjUnSZbzVOGphvqt5hjl5Eo6ZcaLkuE4QLLAcczoUsH35L3qRk4+9mbGaUWSsXLOp9u+okt/gv9gGyTkTatVcQuEw4A89ElSqoL+XmXIrOYEUqoesfG1/JzoXYRjRwTBg0Gcryv3mmHgDQMg1/dPKgYSdNDTCBKqH9xG8VF6u5pTM0ZVJDw7gmFxEak74hTNNYtccyZ5/kfws1Ohh2U+ow5cQntzPbvbh3J0F0cGascI5Zu+ECMlI7n3x+H9or6Gi7OqNAaU5t65PLVEA=
