language: python
python:
- 2.7
before_install:
- sudo apt update
- sudo apt install -y libcurl4-openssl-dev libssl-dev
script:
- echo "no test specified"
stages:
- deploy
deploy:
  provider: pypi
  user: __token__
  password:
    secure: WmmV77lt9pZFuGg4hWklMjwZ6Emz4A5jxFbruv9ZVJXDK+ad6G73JlWM0gnH5mRz4gQEnTm5UPkItXtQ48vNbkBUKm6v4tjwtwzT1dLLKqyTRfwmB26jyeEMr0TqHjOgmrvIAoSdrCVSn1CeW/ddqXbFeH6JfwG6QVnuqcvQ3tRtQ83X4NcOB/mQ+VGu3CElxQ1jN36b+4ZPl31UaNoaNDxU2Ye5/TmXqVhFkKqoSTOklOrKG5xEj86LAvQOtaPFSMR3qI2ugJN86ddb/gxO1j1JlfphFhOROrpBkKyNIeSbaMyv73vKaWtougWxjEzxSmVManlk+HCStnQWKqmZC68pR0UunFpGtFiHxNwTGEzqMy4uDXZnzF4gLq03sbPlemIHyw/RgV3PyKP+VKW1O6TzO2YDZ8j2ak8ATugPCFmJmG9Nzt994JhOEHxvWAVPqC6UdS1Rxbn6lCVg0PSM0nRdC3WWiQp/BFHrFZ4v3zHtvbMhUrA/CztOJM9HSweLjgkvkzN9Z8jGQgeiEsp3+Xs/x3DmlewTVxtfViWJAXY4FH5Uoak23w/7DnskMsLlwZ0kcyfBlUHpIWPBfmYnc0sSYkoeZUvU43ViCccek2XMYR1QUMk9Dax5vf/8x4t23dSU2a+IynbYklsvMsicW6TWKcpks5zZkX9ej4j++dk=
