dist: focal
language: python
env:
  matrix:
  - PYTHONIOENCODING=utf-8
  global:
    secure: EH5Y54XE/Zf1ln+nQN+Dczwv6u+/29ihLEBrr8wncPQ7aJtwB9DDCqXe3HpRDMzE9PGEMTZkjb33Y1l0afUPUA7twOeGueVllwRjhW4BHLc0DaWNLRoCDDCbrrVtbMyv/64yxnV/cmVyA1bVj0LNFVuW9xeGUdcgR5nVKIw9z5MfU3szJW66P8U8hpugZ8ONp7TaEl4DVBZMJjij9AehSCGY1ye6MPjanNtwXFmAMUqX7nWEZhcNrgSvK3X1ECK19tcjhIOKAwBhv6x2Mclc3gurkbniDE3qhfGVX/G3GWtkTxq4vZsrwtPoFz+hopYQCU7AFqM3U2Ex9DMSxlL3S7wcFz6PuRgAqHn66Wp+OPfWzONUkmp+lfiazZ8BJlewCkD49+3TU6glyWsvt+lMvCbpT4mImkYkxD9O766Bmw0SzTKTxR5DeZRUm37bQl08HVoeqD3Qc9Fk8w690CbsMZniQ82VSzn2hy+1cI3B+H3m2JwZABxBKQv+yyiCHSa9FqyM+AGvG13iwyra7vhOVUKO86zT9efQiGXviIkK+L6tJGaJGo+Hclek3cX9keKK2hgAxADWj0h02aVV2W4YsDEmDNn2lKEu5PicEYdpL+WNJTj72uAFWLGMCWuYBzmu7tKBg1R0IxOg8Agr2HMijqS+iyDWsuGvFD3DNYVSoIk=
python:
- '3.8'
- '3.9'
- 3.9-dev
- nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
    - postfix
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
- cat maincfpatch | sudo tee -a /etc/postfix/main.cf
- sudo bash install_rspamd.sh
- sudo systemctl restart postfix
- sudo systemctl restart rspamd
script:
- python3 -m unittest discover -v
stages:
- deploy
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u entroserv --password-stdin
- docker build -t entroserv/cryptdomainmgr .
- docker push entroserv/cryptdomainmgr
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: vYysmnM+BTHfH3arLIkjttwKTDeqHOyWuhHfaVC8acUU7Fvc06hJtD7J8IMsdEeKe6H0qnz4lhK3QCCMKXWgh3lBHpSGMzvklkAbcna7wr+bgiARn1NLG3Gs+U1YqMagUBWQoi5LlRSjbYwNqiLh78xA85WXXLF1NPvNuy9nOdNF7VTIhSY+fT8/HtpHoFhy0cN2+WWb6EWJGdp+uB8t4PP3x436WjA6NsRI1T4XNXALFuv10puoi+oEFpHe9iGqKlYyNTtA9UyM1oSJpvxMJD+ISOgcYgi67i84MRsVLC/krV9u/JBFauL5gCeQEDLg60El8zz0kGH8PONM3EM4SdIrzKCNoOha+W08N42BzpSWOoj1J8FdZHnLPnZNH+VjbZCG/5iN5yiBOG5DzKKmy0d4fUcjUnSZbzVOGphvqt5hjl5Eo6ZcaLkuE4QLLAcczoUsH35L3qRk4+9mbGaUWSsXLOp9u+okt/gv9gGyTkTatVcQuEw4A89ElSqoL+XmXIrOYEUqoesfG1/JzoXYRjRwTBg0Gcryv3mmHgDQMg1/dPKgYSdNDTCBKqH9xG8VF6u5pTM0ZVJDw7gmFxEak74hTNNYtccyZ5/kfws1Ohh2U+ow5cQntzPbvbh3J0F0cGascI5Zu+ECMlI7n3x+H9or6Gi7OqNAaU5t65PLVEA=
