dist: focal
language: python
env:
  matrix:
  - PYTHONIOENCODING=utf-8
  global:
    secure: edJqvUIrRlVqCgpg8ssjO2cm6oXlpYCUNGSoL5o0cvZg+EUTXb7rxQJDSg2gH8OxxE5GR9DMJSaRnsphDR+M+A3DvO34uUXdbo3KPTL2YjwkCPBJ6Ok8dMo+rfW/Ij9PuTABA85grupqyZVmp3AZLA5CQUo8XHT8iV6fM5jpYw494AtphsemAvsxvXxvGZCNrLQc7E2gkfJrCOXPHqgSjgM0vIDl6qSeEPOQO63D0I2ITvM4pEXreQYih5QeUyRLCt9+dGIY6U3Q8gZnTk+5/C3C34K1FDX/UV9pILYZtaw7JeD6heC9NQsq947M39fTysZGE5JUzvRpTbH6r+qYh0jlZq08jg1+vHSGphb1NarbH5PgkMd3OgExHNDmCQQ52the6BD1glRLZOSMAtCZktdc51BO9x0Hlo10+rtPN7jx54c2ljLrUfMlg4BR4X9d6A3kZjEoyGUtH4CK2OxKGuDBkHMdmPERDwZJV5RAFdwTxFGq3Nz+Y2jJ8PowLvUbEU5U97hHOYchemUhWYkdzkL0SUOFtT5tDzfx79peEuH0vkQf9FxIcVmLJwvq9hQnDyllEhW3bc+LwRs9K2oBZ2WIPWGRnHmCfqDdJCMWJuNYVZKvmjqwcYvMMyn/a1jLW1whGq9DANwstXZO0YAKe6QVTRdfTpIco9AnxxNvEgA=
python:
- '3.8'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
    - postfix
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
script:
- echo "hello"
stages:
- deploy
after_success:
- echo "${DOCKER_PASSWORD:0:2}"
- echo "$DOCKER_PASSWORD" | docker login -u entroserv --password-stdin
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: vYysmnM+BTHfH3arLIkjttwKTDeqHOyWuhHfaVC8acUU7Fvc06hJtD7J8IMsdEeKe6H0qnz4lhK3QCCMKXWgh3lBHpSGMzvklkAbcna7wr+bgiARn1NLG3Gs+U1YqMagUBWQoi5LlRSjbYwNqiLh78xA85WXXLF1NPvNuy9nOdNF7VTIhSY+fT8/HtpHoFhy0cN2+WWb6EWJGdp+uB8t4PP3x436WjA6NsRI1T4XNXALFuv10puoi+oEFpHe9iGqKlYyNTtA9UyM1oSJpvxMJD+ISOgcYgi67i84MRsVLC/krV9u/JBFauL5gCeQEDLg60El8zz0kGH8PONM3EM4SdIrzKCNoOha+W08N42BzpSWOoj1J8FdZHnLPnZNH+VjbZCG/5iN5yiBOG5DzKKmy0d4fUcjUnSZbzVOGphvqt5hjl5Eo6ZcaLkuE4QLLAcczoUsH35L3qRk4+9mbGaUWSsXLOp9u+okt/gv9gGyTkTatVcQuEw4A89ElSqoL+XmXIrOYEUqoesfG1/JzoXYRjRwTBg0Gcryv3mmHgDQMg1/dPKgYSdNDTCBKqH9xG8VF6u5pTM0ZVJDw7gmFxEak74hTNNYtccyZ5/kfws1Ohh2U+ow5cQntzPbvbh3J0F0cGascI5Zu+ECMlI7n3x+H9or6Gi7OqNAaU5t65PLVEA=
