dist: focal
language: python
env:
  matrix:
  - PYTHONIOENCODING=utf-8
  global:
    secure: udBm3gFvBnZx8Xlc/0Ka9e487T8Ry/H0JSpd2adclB0jqaGWWcOMHv2AAuryHzsnL+tLG613J6+nISd72IJuxvxJl5ZHw+JjG5IC3Tq4KtyqaYHulbnlQvBaMWLuIJ34GG3+QxXpLBFTbEhOcCrJL/zuIfYNGL+hizYb1GHxYReTVMkEm7I42OPOofLzCj35910tfJTOz8sxuAQi/MGwmZzwaCpTi8133S1n/9a0Bc1kyNHm6W7lZVjEPHq0f6t88ZnsQ3bKfYNullGG+vS5n2GgsFWJNwca/++GNDizPICl+1/YkSjfkjHG7fdZfkHaW0OGntV4Fu6hJwzsK2YGBVUySCF5RdFo0U1YehC7UyFL+bH5fC3jR1Gyhb0LgMN2l2HaiG/jn7hl0VIQptDp5wgsTxnCnIdTR2hQQQK7cJ86oTejFSoLIXKjsOKyyxDOc4asasnoLXZzCddAvXpY6GYoenfJEpgpjxNRZOMp5VezPOTcgGE94/mxFGtnSZYoW4pTCkzAvPigOvJ0du5a/OdUMTu5Ioe71XQ9o2TlTTeOazwFIr9wC8PE0Tb2Zr5zXlIwKkoy0pdT8UY4jPmD5W0vXId7UWIWcqbR2P7p99fgSOCem+ljEhyWeFvaBabKvoCSzF1qMu2M+vt/JRrRvFLGE4qv3M92DPbA/5gr21g=
python:
- '3.8'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
    - postfix
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
script:
- echo "hello"
stages:
- deploy
after_success:
- echo "${DOCKER_PASSWORD:0:5}"
- echo "$DOCKER_PASSWORD" | docker login -u entroserv --password-stdin
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: vYysmnM+BTHfH3arLIkjttwKTDeqHOyWuhHfaVC8acUU7Fvc06hJtD7J8IMsdEeKe6H0qnz4lhK3QCCMKXWgh3lBHpSGMzvklkAbcna7wr+bgiARn1NLG3Gs+U1YqMagUBWQoi5LlRSjbYwNqiLh78xA85WXXLF1NPvNuy9nOdNF7VTIhSY+fT8/HtpHoFhy0cN2+WWb6EWJGdp+uB8t4PP3x436WjA6NsRI1T4XNXALFuv10puoi+oEFpHe9iGqKlYyNTtA9UyM1oSJpvxMJD+ISOgcYgi67i84MRsVLC/krV9u/JBFauL5gCeQEDLg60El8zz0kGH8PONM3EM4SdIrzKCNoOha+W08N42BzpSWOoj1J8FdZHnLPnZNH+VjbZCG/5iN5yiBOG5DzKKmy0d4fUcjUnSZbzVOGphvqt5hjl5Eo6ZcaLkuE4QLLAcczoUsH35L3qRk4+9mbGaUWSsXLOp9u+okt/gv9gGyTkTatVcQuEw4A89ElSqoL+XmXIrOYEUqoesfG1/JzoXYRjRwTBg0Gcryv3mmHgDQMg1/dPKgYSdNDTCBKqH9xG8VF6u5pTM0ZVJDw7gmFxEak74hTNNYtccyZ5/kfws1Ohh2U+ow5cQntzPbvbh3J0F0cGascI5Zu+ECMlI7n3x+H9or6Gi7OqNAaU5t65PLVEA=
