dist: focal
language: python
addons:
  apt:
    packages:
    - python3
    - rspamd
    - libcurl4-openssl-dev
    - libssl-dev
    - postfix
before_install:
- openssl aes-256-cbc -K $encrypted_e70009473049_key -iv $encrypted_e70009473049_iv
  -in test_inwxcreds.conf.enc -out test_inwxcreds.conf -d
- cat maincfpatch | sudo tee -a /etc/postfix/main.cf
- sudo systemctl restart postfix
script:
- sudo bash -c "source $VIRTUAL_ENV/bin/activate && $VIRTUAL_ENV/bin/python3 -m unittest
  discover"
stages:
- deploy
deploy:
  provider: pypi
  user: __token__
  password:
    secure: xoagD/QefZp7Uw6WDfa5FMMq0Fx9YGFwQolTRxODiU59uKIn5lOjw0vpUNYX7NwFg+wlmgxBJ5zuolAOKLk+G42PT1V51PimAd3iT23/7ipdSQF5NFGeNuxIbdvgYYCeg8EzwiVdRTzuRRum9/MA2HORbck88Vsu/uoClsbXcEIPa33KuNXgVUQHq06d+lS5B7xSYGwtwjX5+4fx8uDh74q/sfSafFbC/BWDh7ZekFEgF/V+XujQff4X35RppASU12LedQwwHVuJyNnIjsgOUQgp59WAIhsgCWEJuZ6mTX0PSvnt3hl3NS5VtlWgPGAtzPdwB6iVOpBVA96mmgtdOBn/6uX2n2O5yKyxRcJllua2PvtpGDrDRnFapkubiOzlWrN4w730Z20J+AZ5EexVYnTLfS5sCNgXD8rAl9J/tnHd/mCxta+YwAFfoZPklOGtxv8Su4slrks/cc/ZYtn5xU9SfMo7LkEaWat2o8pBTAlVqz/wmGUfFZl+IoPMYc0hTRAO3l6743aFmZmE3saeh0C+efDBxeQpEuRzstRWpHaAcEf0gsornU3pKvO7fZI6wYl6/J8kUfx/SC4F4TE3ySdwkIEmzFACrR6NRC7YfJKm4+nT5/Hy9NgBXDAHOaf7yJCOJzOHuqlKNxBH3+UZVcPsbGvQdg3aVE5BkXu3Pfw=
