---

- hosts: local
  user: stefan
  vars_files:
    - vars/common.yml

  tasks:
  
    - name: Secondary domains as csv
      set_fact:
        secondary_domains_csv: "{% if secondarydomains %}{% for d in secondarydomains %}{{ d }}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}" 
  
    - name: All domains as csv
      set_fact:
        domains_csv: "{{ domain }}{% if secondary_domains_csv %},{% endif %}{{ secondary_domains_csv }}" 
  
    - name: debug
      debug:
        msg: "{{ domains_csv }}"

