---

- hosts: crm-server
  user: root
  vars_files:
    - vars/common.yml
    - vars/database.yml
    - vars/mail.yml
    - vars/lists.yml
    - vars/tine.yml
    - vars/cert.yml
    - vars/passwords.yml
    - vars/inwx.yml
    - vars/inwxpasswd.yml
  roles:
    - common
    - mailserver
    - domain


  tasks:
    - name: Start handler for domain
      shell: "echo \"run handler\""
      notify:
        - domain update
