---

- name: Clone amavisd-milter
  git:
    repo: "https://github.com/ThomasLeister/amavisd-milter.git"
    dest: "/root/amavisd-milter"

- name: Install amavis
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - amavisd-new
    - libmilter-dev
    - spamassassin
    - acl
    - python-pylibacl

- name: Build amavisd-milter
  shell: "touch * && ./configure && make && make install"
  args:
    executable: "/bin/bash"
    chdir: "/root/amavisd-milter"

- name: Copy /etc/init.d/amavisd-milter
  copy:
    dest: /etc/init.d/amavisd-milter
    src: ../files/etc/init.d/amavisd-milter

- name: Copy /etc/systemd/amavisd-milter.service
  copy:
    dest: /etc/systemd/amavisd-milter.service
    src: ../files/etc/systemd/amavisd-milter.service

- name: Permissions of amavisd-milter init
  file:
    name: /etc/init.d/amavisd-milter
    mode: 0755
    state: file

- name: Process amavis templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/amavis/{{ item.path }}"
  with_filetree: "../templates/etc/amavis/"
  when: item.state == 'file'
  notify:
    - Restart amavis
    - Restart amavisd-milter

- name: Permissions /etc/amavis/conf.d/50-user
  file:
    path: /etc/amavis/conf.d/50-user
    owner: root
    group: root
    mode: 770
    state: file

- name: Create /var directories 
  file:
    path: "{{ item }}"
    owner: "{{ deliver_user_name }}"
    group: "{{ deliver_user_name }}"
    mode: 0770
    state: directory
  with_items:
    - "/var/mail"
    - "/var/mail/sieve"
    - "/var/mail/sieve/global"

- name: Copy /var/mail files
  copy:
    dest: /var/mail/
    src: ../files/var/mail/

- name: Permissions and owner /var/mail/sieve
  file:
    path: /var/mail/sieve
    owner: "{{ deliver_user_name }}"
    group: "{{ deliver_user_name }}"
    state: directory
    recurse: yes

- name: Permissions and owner /var/mail/spampipe.sh
  file:
    path: /var/mail/spampipe.sh
    owner: "{{ deliver_user_name }}"
    group: "{{ deliver_user_name }}"
    mode: 774
    state: file
  notify:
    - Restart amavis
    - Restart amavisd-milter



