---

- name: Escape dkimkey
  set_fact:
    dkimkeyescaped: "{{ dkimkey|replace('\"','\\\"') }}"
  listen: "domain update"

- debug: 
    msg: "{{ dkimkeyescaped }}"
  listen: "domain update"

- name: "Update domain {{ item }} on inwx"
  shell: "/root/inwxupdate.bash \"{{ inwxapi }}\" \"{{ inwxlogin }}\" \"{{ inwxpasswd }}\" \"{{ item.split('.',1)[0] }}\" \"{{ item.split('.',1)[1] }}\" \"{{ myextip }}\" \"{{ myextip6 }}\" \"{{ dkimkeyescaped }}\" 600" 
  args:
    executable: "/bin/bash"
  listen: "domain update"
  with_items:
    - "{{ domain }}"
    - "{{ secondarydomains }}"
  ignore_errors: yes


