version: "3.3"

services:


  cdm:
    build:
      context: ..
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configuration/:/configuration/"
      - "../exampleconf/:/etc/cryptdomainmgr/"
    command:
      - "[cdm]  postwait=5"


  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--log.level=DEBUG"


    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configuration/:/configuration/"

  whoami:
    image: "traefik/whoami"
    container_name: "simpleservice"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`test1337x.bahn.cf`)"
      - "traefik.http.routers.whoami.tls=true"
        #- "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.entrypoints=web-secure"

