---


- name: Configure mailman create_site_list
  debconf:
    name: mailman
    question: mailman/create_site_list
    value: true 
    vtype: note

- name: Configure mailman site_language
  debconf:
    name: mailman
    question: mailman/site_languages
    value: de
    vtype: multiselect

- name: Install mailman
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mailman
  #notify:
  #  - Newlist mailman

- name: Create directories 
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "/etc/mailman"

- name: Process mailman templates
  template:
    src: "{{ item.src }}"
    dest: "/etc/mailman/{{ item.path }}"
  with_filetree: "../templates/etc/mailman/"
  when: item.state == 'file'
  notify:
    - Restart mailman

- name: Configure mailman
  blockinfile:
    dest: "/etc/mailman/mm_cfg.py"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - {{ item["webdomain"] }}: {{ item["emaildomain"] }}'
    content: |
      add_virtualhost( '{{ item["webdomain"] }}', '{{ item["emaildomain"] }}' )
#   content: |
#     add_virtualhost( '{{ mailman_prefix }}.{{ item }}', '{{ mailman_prefix }}.{{ item }}' )
  with_items:
    - "{{ listmaps }}"
   #- "{{ domain }}"
   # - "{{ secondarydomains }}"

- name: Add mailman to apache2
  template:
    dest: "/etc/apache2/sites-available/mailman.conf"
    src: "../templates/etc/apache2/sites-available/mailman.conf"

- name: Add mailman domains to apache2
  blockinfile:
    dest: "/etc/apache2/sites-available/mailman.conf"
    insertbefore: "^# Ansible block position"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - {{ item["webdomain"] }}: {{ item["emaildomain"] }}'
    content: |
      <VirtualHost *:80>
          ServerName {{ item["webdomain"] }}
          Redirect / https://{{ item["webdomain"] }}/
      </VirtualHost>
  with_items:
    - "{{ listmaps }}"
   #- "{{ domain }}"
   #- "{{ secondarydomains }}"

- name: Add mailman domains to apache2 - ServerAlias
  blockinfile:
    dest: "/etc/apache2/sites-available/mailman.conf"
    insertafter: "^# ServerAliases"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Aliases {{ item["webdomain"] }}'
    content: |
      ServerAlias {{ item["webdomain"] }} {{ mailman_prefix }}.{{ domain }} 
  with_items:
    - "{{ listmaps }}"


- name: Activate cgid in apache2
  apache2_module:
    state: present
    name: cgid
    ignore_configcheck: true
  ignore_errors: true

- name: Activate mailman in apache2
  shell: "a2ensite mailman.conf"
  args:
    executable: "/bin/bash"
  notify:
    - Restart apache2

- name: Add user postfix to group list
  user:
    name: postfix
    groups: list
    append: yes  

- name: Set list creators password
  shell: "mmsitepass {{ list_creators_passwd }}"
  args:
    executable: "/bin/bash"

- meta: flush_handlers

- name: Newlist mailman
  shell: 'echo -e "\n" | /usr/sbin/newlist mailman {{ mailman_email }} {{ mailman_passwd }}'
  args:
    executable: /bin/bash
  ignore_errors: True

  #- name: Initial list must be created to generate virtual-mailman
  #  meta: flush_handlers

  #- name: Mailman genaliases
  #  shell: '/var/lib/mailman/bin/genaliases'
  #  args:
  #    executable: /bin/bash

- name: Permissions for /var/lib/mailman/data/aliases.db
  file:
    name: /var/lib/mailman/data/aliases.db
    state: file
    owner: www-data
    group: list

- name: Permissions for /var/lib/mailman/data/virtual-mailman.db
  file:
    name: /var/lib/mailman/data/virtual-mailman.db
    state: file
    owner: www-data
    group: list


