---

- name: Init postfix db
  mysql_db:
    name: postfix
    state: import
    target: /tmp/postfix.sql
    login_user: root
    login_password: '{{ mysql_root_passwd }}'

- name: Restart postfix
  service:
    name: postfix
    state: restarted




